# Generated by Django 2.2.6 on 2019-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figuras',
            fields=[
                ('id_figura', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fugura', models.CharField(max_length=120)),
                ('num_figura', models.CharField(max_length=3)),
            ],
        ),
    ]
