# Generated by Django 2.2.6 on 2019-10-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuras',
            name='num_figura',
            field=models.IntegerField(default=0),
        ),
    ]
